"""Add PackageQRCode model for individual package tracking

Revision ID: 02abd9cbe72d
Revises: 1bb685565426
Create Date: 2025-09-13 12:51:46.404099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02abd9cbe72d'
down_revision = '1bb685565426'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('package_qr_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('package_number', sa.Integer(), nullable=False),
    sa.Column('unique_code', sa.String(length=12), nullable=False),
    sa.Column('qr_code_url', sa.String(length=255), nullable=False),
    sa.Column('qr_image_path', sa.String(length=255), nullable=True),
    sa.Column('package_type', sa.String(length=50), nullable=True),
    sa.Column('package_description', sa.String(length=200), nullable=True),
    sa.Column('package_weight', sa.String(length=20), nullable=True),
    sa.Column('package_dimensions', sa.String(length=100), nullable=True),
    sa.Column('attention_person_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['attention_person_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipment.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unique_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('package_qr_code')
    # ### end Alembic commands ###
