"""Add SMTP configuration table

Revision ID: 3a2141887292
Revises: 02abd9cbe72d
Create Date: 2025-10-09 13:15:18.686759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a2141887292'
down_revision = '02abd9cbe72d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('smtp_configuration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('mail_server', sa.String(length=255), nullable=False),
    sa.Column('mail_port', sa.Integer(), nullable=False),
    sa.Column('mail_use_tls', sa.Boolean(), nullable=False),
    sa.Column('mail_use_ssl', sa.Boolean(), nullable=False),
    sa.Column('mail_username', sa.String(length=255), nullable=False),
    sa.Column('mail_password', sa.Text(), nullable=False),
    sa.Column('mail_default_sender', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('smtp_configuration')
    # ### end Alembic commands ###
