"""Add PI ID to users and create InvoiceCounter table

Revision ID: 4af799bc00db
Revises: 5cb52fc6d689
Create Date: 2025-06-19 23:34:11.790174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4af799bc00db'
down_revision = '5cb52fc6d689'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pi_id', sa.String(length=10), nullable=False))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('given_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.create_unique_constraint(None, ['pi_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('given_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('pi_id')

    # ### end Alembic commands ###
