"""Initial migration

Revision ID: 5cb52fc6d689
Revises: 
Create Date: 2025-06-16 21:01:51.476103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cb52fc6d689'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipment', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'signing_authority', ['signing_authority_id'], ['id'])
        batch_op.drop_column('country_of_final_destination')
        batch_op.drop_column('country_of_origin')
        batch_op.drop_column('mode_of_transport')
        batch_op.drop_column('port_of_discharge')
        batch_op.drop_column('final_destination')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('final_destination', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('port_of_discharge', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('mode_of_transport', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('country_of_origin', sa.VARCHAR(length=100), server_default=sa.text("'India'"), nullable=True))
        batch_op.add_column(sa.Column('country_of_final_destination', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
