"""Make PI ID required and add unique constraint

Revision ID: dc9a2244290f
Revises: 4af799bc00db
Create Date: 2025-06-19 23:35:36.347092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc9a2244290f'
down_revision = '4af799bc00db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('pi_id',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.create_unique_constraint(None, ['pi_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('pi_id',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)

    # ### end Alembic commands ###
